### ISSUE TITLE
Bug: calcite-radio-button and calcite-radio-group-item issues

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1027]
### Summary

In both cases I have 2 buttons or group-items. I only listen to the change event handler of the first button or group-item and enter different async workflows depending if event.target.checked is true or false.

Note: all these issues go away if I use event.stopPropagation() and listen to the change event for both buttons and group-items and only act if checked is true. Also, I need to add name, scale, span to radio-buttons.

Issues 1. and 2. must have started after beta.37, which is what we use in MVB on production. 
I mostly tested with beta.40 and next.9 from today with a test app outside of MVB, but with using Maquette.

- [x] 1. `calcite-radio-group-item` (moved to https://github.com/Esri/calcite-components/issues/1058)
I seem to have to call event.stopPropagation() in the change event handler, otherwise the change event gets called 3 times in a row with different event.target.checked settings _after_ the component gets recreated in Marquette in the afterCreate property. I verified, via a timestamp, that the event handler that is called 3 times is the one that was created last by afterCreate. No event handler left-overs from the original creation of the component. Maybe this has something to do with the clean-up not working correctly.
True/false is the checked state, the last 3 change event calls come from a single click.
<img src=https://user-images.githubusercontent.com/44481292/94075685-7e1b2100-fdb0-11ea-91e2-4c67d1c6d3b4.png width=200/>
<img src=https://user-images.githubusercontent.com/44481292/94082935-dbb26c00-fdb6-11ea-98ea-d1123b849f89.png width=200/>

- [x] 2. `calcite-radio-button`
This only happens if I start with the second button checked, the one that doesn't listen to the change event. After the second toggle it gets in the state that both radio buttons are checked. I noticed that in this case it does not call the un-check change event on the first button.
-> this is expected now, no more change event on un-check; double check is fixed
<img src=https://user-images.githubusercontent.com/44481292/94075565-4a3ffb80-fdb0-11ea-8f8b-12121e969817.png width=150/>

- [x] 3. `calcite-radio-button`
This is new with next.9, didn't happen with beta.40. It no longer calls the change event for a radio button that gets un-checked.
-> it seems this is purpose now

- [x] 4. `calcite-radio-button`
When removing my component I see this.
Might be related to this https://github.com/Esri/calcite-components/issues/977
<img src=https://user-images.githubusercontent.com/44481292/94078437-08648480-fdb3-11ea-8624-020b96f332ca.png width=300/>

- [x] 5. `calcite-radio-button`
Tested with next.9. Kevin mentioned to add `name` and `scale` to calcite-radio-button and add the label inside a `span` element. 
Without it this is what I see: Size/font is messed up the second time the radio buttons load because the text is not wrapped in calcite-label.
first time
<img src=https://user-images.githubusercontent.com/44481292/94085818-fcca8b00-fdbd-11ea-8c10-a70c87136a4c.png width=200/>
second time
<img src=https://user-images.githubusercontent.com/44481292/94085862-1d92e080-fdbe-11ea-8d98-dd1804b4cd9f.png width=210/>

Do we need to update the doc and mention the span?
![image](https://user-images.githubusercontent.com/44481292/94085105-07842080-fdbc-11ea-82c3-f2c28e11a5b7.png)
![image](https://user-images.githubusercontent.com/44481292/94085119-1074f200-fdbc-11ea-95e3-72fd6cea6c7b.png)

- [x] 6. `calcite-radio-button`
When I add text for a radio-button like `<calcite-radio-button>{text}</calcite-radio-button>` the text is wrapped inside a calcite-label component. This is fine. When I use it this way in my code `<calcite-radio-button>{text1}{text2}</calcite-radio-button>` then text1 and text2 are each wrapped in a calcite-label, not together in a single calcite-label. Is this ok? When I do this ```<calcite-radio-button>{`${text1}${text2}`}</calcite-radio-button>``` it's just one calcite-label.  Resolved by #1195 

Not sure if any of this makes sense, but I don't quite understand what's going on exactly behind the scene.
Also, it might be related to it being used with Maquette. Timing seems to be a bit different there.

### Reproduction Steps

1.

**Comment by kevindoshier** [comment]
cc: @eriklharper - I think this is the same one we were trying to figure out last week

**Comment by kevindoshier** [comment]
This might fix this issue, not completely sure yet

https://github.com/Esri/calcite-components/pull/1011

**Comment by AdelheidF** [comment]
added 5.

**Comment by AdelheidF** [comment]
added 6.

**Comment by eriklharper** [comment]
Issues 2, 4 and 5 seem to be addressed on `next.10` with the fixes I applied on #1011.

**Comment by AdelheidF** [comment]
Tested with `next.10`.

Test case for #3, because of this issue I can't get to test #2 anymore.

<details>
  <summary>code change</summary>
  
  /src/smartMapping/support/Age/index.tsx
```
  private _renderRotationType(tsx: H) {
    const { layer } = this.props;
    const renderer = layer.renderer as any;
    const rotationVisVar: RotationVariable = getVisVar(renderer, "rotation") as RotationVariable;

    let leadingDegree = false;
    if (i18n.ui.rotateZeroDegrees.indexOf("°") === 0) {
      leadingDegree = true;
    }

    return (
      <div class={`${CSS.rotationType} ${CSS.blockContentPadding}`}>
        <calcite-radio-button-group class={CSS.rotationTypeSelection} name="rotationType" scale="s">
          <calcite-radio-button
            checked={rotationVisVar.rotationType === "geographic"}
            afterCreate={(node: HTMLElement) => {
              node.addEventListener("calciteRadioButtonChange", (event: CustomEvent) => {
                event.stopPropagation();
                console.log("calciteRadioButtonChange (for Geographic radio) checked:", (event.target as any).checked);
                if ((event.target as any).checked) {
                  this.handleTypeChange("geographic");
                } else {
                  this.handleTypeChange("arithmetic");
                }
              });
            }}
          >
            {i18n.ui.geographic}
          </calcite-radio-button>
          <calcite-radio-button
            checked={rotationVisVar.rotationType === "arithmetic"}
          >
            {i18n.ui.arithmetic}
          </calcite-radio-button>
        </calcite-radio-button-group>

        <div class={CSS.rotationTypeDisplay} aria-hidden="true">
          {rotationVisVar.rotationType === "arithmetic"
            ? leadingDegree
              ? this._renderRotationSVG_Ari_leading(tsx)
              : this._renderRotationSVG_Ari(tsx)
            : leadingDegree
            ? this._renderRotationSVG_Geo_leading(tsx)
            : this._renderRotationSVG_Geo(tsx)}
          <div
            key={renderer}
            class={CSS.rotationTypeSymbol}
            afterCreate={this._afterCreateSymbol.bind(this)}
          />
        </div>
      </div>
    );
  }
```
</details>

http://devext.arcgis.com/apps/mapviewer/index.html?url=https://servicesdev.arcgis.com/f126c8da131543019b05e4bfab6fc6ac/ArcGIS/rest/services/USA%20Drilling%20Platforms/FeatureServer/0

Click Styles
Click x after 'Water Deapth` to remove it
Wait, scroll down to Age (color) and click on tile to select it
Click again on tile to open advance options
Notice the date display
<img src=https://user-images.githubusercontent.com/44481292/94309244-9c0d9080-ff2c-11ea-9f16-ef53ac20a03c.png width=200/>
Click on Field, notice the field display
Also look at console, it correctly calls the change event
<img src=https://user-images.githubusercontent.com/44481292/94309633-3a99f180-ff2d-11ea-84c5-585f67ce0788.png width=300/>
<img src=https://user-images.githubusercontent.com/44481292/94309286-ae87ca00-ff2c-11ea-81e7-741b69b3d725.png width=200/>
Click on Custom Date, Now field display doesn't become date display because the change event does not get called. Console message for change event does not appear.
<img src=https://user-images.githubusercontent.com/44481292/94309430-eee74800-ff2c-11ea-8437-abaada59d612.png width=200/>

**Comment by AdelheidF** [comment]
Tested with `next.10`.

Test case for #5.
<details>
  <summary>code change (without the workaround)</summary>
  
  /src/smartMapping/support/Rotation/index.tsx
```
  private _renderRotationType(tsx: H) {
    const { layer } = this.props;
    const renderer = layer.renderer as any;
    const rotationVisVar: RotationVariable = getVisVar(renderer, "rotation") as RotationVariable;

    let leadingDegree = false;
    if (i18n.ui.rotateZeroDegrees.indexOf("°") === 0) {
      leadingDegree = true;
    }

    return (
      <div class={`${CSS.rotationType} ${CSS.blockContentPadding}`}>
        <calcite-radio-button-group class={CSS.rotationTypeSelection} name="rotationType" scale="s">
          <calcite-radio-button
            checked={rotationVisVar.rotationType === "geographic"}
            afterCreate={(node: HTMLElement) => {
              node.addEventListener("calciteRadioButtonChange", (event: CustomEvent) => {
                event.stopPropagation();
                console.log("calciteRadioButtonChange (for Geographic radio) checked:", (event.target as any).checked);
                if ((event.target as any).checked) {
                  this.handleTypeChange("geographic");
                } else {
                  this.handleTypeChange("arithmetic");
                }
              });
            }}
          >
            {i18n.ui.geographic}
          </calcite-radio-button>
          <calcite-radio-button
            checked={rotationVisVar.rotationType === "arithmetic"}
          >
            {i18n.ui.arithmetic}
          </calcite-radio-button>
        </calcite-radio-button-group>

        <div class={CSS.rotationTypeDisplay} aria-hidden="true">
          {rotationVisVar.rotationType === "arithmetic"
            ? leadingDegree
              ? this._renderRotationSVG_Ari_leading(tsx)
              : this._renderRotationSVG_Ari(tsx)
            : leadingDegree
            ? this._renderRotationSVG_Geo_leading(tsx)
            : this._renderRotationSVG_Geo(tsx)}
          <div
            key={renderer}
            class={CSS.rotationTypeSymbol}
            afterCreate={this._afterCreateSymbol.bind(this)}
          />
        </div>
      </div>
    );
  }
```
</details>

http://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0&portal=https://devtesting.mapsdevext.arcgis.com/sharing/rest

Click Styles
Click on Location tile to get to advanced option
Click on Rotation section, look at font of radio buttons
Click Cancel at bottom of the panel
Click on Location tile to get to advanced option
Click on Rotation section, look at font of radio buttons

Some times you get the wrong font the first time and sometimes the second time, but it seems to switch every other time.

**Comment by AdelheidF** [comment]
Tested with `next.10`.

Test case for #1 .
<details>
  <summary>code change (removed workaround of event.stopPropagation())</summary>
  
  /src/smartMapping/Size/index.tsx
```
  private _renderSizeRange(tsx: H) {
    const { layer, mapImageSublayer } = this.props;
    const renderer = layer.renderer as ClassBreaksRenderer;
    const sizeVisVar = getVisVar(renderer, "size") as SizeVariable;
    const isNull = sizeVisVar ? !isDefined(sizeVisVar.minSize) : false; // then we have stops (= fixed)
    const isNumber = sizeVisVar ? typeof sizeVisVar.minSize === "number" : false;
    const isAutomatic = !isNull && !isNumber;

    if (sizeVisVar && !mapImageSublayer) {
      return (
        <div key="size-range" class={`${CSS.sizeRange} ${CSS.blockContentPadding}`}>
          <div key="size-range-label" class={CSS.sizeRangeLabel}>
            {i18n.ui.sizeRange}
          </div>
          <calcite-radio-group class={CSS.sizeRangeButtons} name="sizeRange" scale="s">
            <calcite-radio-group-item
              checked={isAutomatic}
              value="automatic"
              class={CSS.sizeRangeButton}
              afterCreate={(node: HTMLElement) => {
                node.addEventListener("calciteRadioGroupItemChange", (event: CustomEvent) => {
                  console.log("calciteRadioGroupItemChange (for Automatic item) checked:", (event.target as any).checked);
                  if ((event.target as any).checked) {
                    this.handleSizeRangeChange("automatic");
                  } else {
                    this.handleSizeRangeChange("fixed");
                  }
                });
              }}
            >
              {i18n.ui.automatic}
            </calcite-radio-group-item>
            <calcite-radio-group-item
              checked={!isAutomatic}
              value="fixed"
              class={CSS.sizeRangeButton}
            >
              {i18n.ui.custom}
            </calcite-radio-group-item>
          </calcite-radio-group>
          {isNull || isNumber ? this._renderSizeRangeFixed(tsx) : null}
        </div>
      );
    } else {
      return (
        <div key="size-range" class={`${CSS.sizeRange} ${CSS.blockContentPadding}`}>
          <div key="size-range-label" class={CSS.sizeRangeLabel}>
            {i18n.ui.sizeRange}
          </div>
          {this._renderSizeRangeFixed(tsx)}
        </div>
      );
    }
  }
```
</details>

http://devext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0

Click Styles
Click +Field, select Fatalities and click Add
Wait, then click first orange dotted tile.
Look below the slider at the 2 buttons, click Custom and watch the console messages. You'll see one change handler message. Good.
Click Done at the bottom of the panel.
Click first orange dotted tile again.
Now the Custom button is selected, this is the one without the change handler.
Clear your console then click the Automatic button and watch the console, especially the messages for the change handler. You should see only one, but you'll see many. The error you get in the console is a result of this issue because the renderer has not changed between those change calls.

<img src=https://user-images.githubusercontent.com/44481292/94322309-fe738a80-ff46-11ea-9605-9439d0298bca.png width=300/>

**Comment by eriklharper** [comment]
Issue https://github.com/Esri/calcite-components/issues/1027#issuecomment-699121744 fixed by #1041

**Comment by AdelheidF** [comment]
#2,#3,#5 verified with `beta.41`.

**Comment by eriklharper** [comment]
> 2,3,5 verified with `1.0.0-beta.41`.

Does verified mean resolved?

**Comment by AdelheidF** [comment]
> Does verified mean resolved?

yes, all good now with the new `calciteRadioButtonGroupChange` event too. Also, single radio buttons no longer get the change event on un-check.

4 is still reproducible for me.

**Comment by eriklharper** [comment]
This can be closed as the items have all been addressed in separate issues.
