### ISSUE TITLE
No cursor appears and characters cannot be inputted in the dropdown box after making a selection in Specific time zone option of InputTimeZone

### ISSUE THREAD

**Issue by thming** [Esri/calcite-components#13146]
**monday.com sync:** #18207248676

### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Which Component

input-time-zone

### Actual Behavior

https://github.com/user-attachments/assets/bff4ca01-85a8-41c5-b405-b7f93ab89d3c

### Expected Behavior

The input and select/dropdown elements should work as expected separately, regardless of how many times the user has made a selection.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/input-time-zone/#sample

### Reproduction Steps

1. Click the input area, and a time zone dropdown menu displays.
2. Click 1-3 times inside the dropdown box (first make three selections), then try to input characters. (key step)
3. Notice that you cannot input anymore, with the key up incident, the dropdown/select collapses, and there is no way to type in anything

### Reproduction Version

The latest version

### Relevant Info

Found in Chrome & Edge. Not reproduced in FF or Safari

### Priority impact

impact - p1 - need for current milestone

### Impact

This would count as a blocker when users try to search for a specific time zone.

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Experience Builder

**Comment by thming** [comment]
cc @geospatialem

**Comment by jcfranco** [comment]
This seems like a duplicate of https://github.com/Esri/calcite-design-system/issues/11643, which was caused by a Chrome bug. If using an older version, could you retest with Chrome v141.0.7390.55 or later?

**Comment by thming** [comment]
@jcfranco, thanks for the info! I've tested it in the latest version chrome, and the issue still occurs
<img width="412" height="151" alt="Image" src="https://github.com/user-attachments/assets/2e8012ff-6db0-4080-8c03-7def273703e0" />

**Comment by jcfranco** [comment]
Thanks for testing. I can reproduce on macOS in 141.0.7390.55, 141.0.7390.77, and 141.0.7390.108. I also tested in 142 (version used to verify the Chromium fix) and 143 and the issue is resolved there. Worth noting that the input caret does not show after the first toggle, but typing still works. cc @Esri/calcite-pes

**Comment by isaacbraun** [comment]
The ability to input/type has been fixed via https://issues.chromium.org/issues/400317114 as Franco mentioned, but the caret/selection does not appear when the parent is focused twice.

A new Chromium Bug for the caret/selection has been opened: https://issues.chromium.org/issues/456432042.

**Comment by jcfranco** [comment]
@isaacbraun I'm not able to see the issue anymore in v147.0.7727.117, so this might be resolved in the latest version of Chrome.

**Comment by isaacbraun** [comment]
@jcfranco Oh interesting. I still see the bug on version `147.0.7727.138` when testing using: https://codepen.io/isaacbraun/pen/PwZdGJZ and the steps listed there. 🤔 Were you focusing the input first? Would love to be wrong here 😆
