### ISSUE TITLE
Enhancement: support highlighting histogram range when slider's min value is negative

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2914]
### Description
Add support for highlighting a histogram range when calcite-slider's `min` prop value is a negative number.

While working on #2457, I'm noticing that slider's track range handles the negative `min` value just fine:

![image](https://user-images.githubusercontent.com/42423180/131000372-7e5b6186-9ab3-48e8-b8ab-6f1f4e231b78.png)

However, when the slider includes histogram data, the highlighted region from calcite-graph doesn't yet align vertically:

![image](https://user-images.githubusercontent.com/42423180/131001709-52783c95-eee8-486a-b813-0ba7e98233c1.png)

### Acceptance Criteria 
When calcite-slider's histogram range has a negative `min` prop value, the highlighted track (ie., in between the `minValue` and `maxValue` data points) aligns with the highlighted histogram region.

### Relevant Info 
calcite-slider's [Range story here](https://esri.github.io/calcite-components/iframe.html?id=components-controls-slider--range&args=&knob-status=idle&knob-scale=m&knob-label%20text=My%20great%20label&knob-type=number&knob-alignment=start&knob-number-button-type=horizontal&knob-min=-100&knob-max=100&knob-step=10&knob-prefix-text=&knob-suffix-text=&knob-value=2020-12-12&knob-placeholder=Placeholder%20text&knob-input%20message%20status=idle&knob-input%20message%20text=My%20great%20input%20message&knob-status_Label=idle&knob-alignment_Label=start&knob-scale_Label=m&knob-layout_Label=default&knob-label%20text_Label=My%20great%20label&knob-type_Input=number&knob-status_Input=idle&knob-alignment_Input=start&knob-number-button-type_Input=horizontal&knob-prefix-text_Input=&knob-suffix-text_Input=&knob-value_Input=&knob-placeholder_Input=Placeholder%20text&knob-active=true&knob-icon_Input%20Message=&knob-input%20message%20text_Input%20Message=My%20great%20input%20message&knob-locale=ar&knob-intl-next-month=Next%20month&knob-intl-prev-month=Previous%20month&knob-switched=true&knob-min-label=Temperature,%20lower%20bound&knob-min-value=-33.32&knob-max-label=Temperature,%20upper%20bound&knob-max-value=30.87&knob-ticks=50&knob-snap=true&knob-histogram[0][0]=0&knob-histogram[0][1]=0&knob-histogram[1][0]=20&knob-histogram[1][1]=12&knob-histogram[2][0]=40&knob-histogram[2][1]=25&knob-histogram[3][0]=60&knob-histogram[3][1]=55&knob-histogram[4][0]=80&knob-histogram[4][1]=10&knob-histogram[5][0]=100&knob-histogram[5][1]=0&knob-label-ticks=true&knob-label-handles=true&knob-histogram%20colors[0]=red&knob-histogram%20colors[1]=green&knob-histogram%20colors[2]=blue&knob-histogram%20color%20offsets[0]=0&knob-histogram%20color%20offsets[1]=0.5&knob-histogram%20color%20offsets[2]=1&knob-precise=false&viewMode=story) shows how it correctly handles the negative min value on the track. Just need to get calcite-graph's highlighted region to match it.

#### Which Components
calcite-slider + calcite-graph

#### Example Use Case
```html
<calcite-slider
  min="-100"
  max="100"
  min-value="-33.32"
  max-value="30.87"
  step="10"
  ticks="50"
  min-label="Temperature range (lower)"
  max-label="Temperature range (upper)"
  class="slider-ex"
  label-handles
  label-ticks
></calcite-slider>
<script>
  document.querySelector(".slider-ex").histogram = [
    [0, 0],
    [20, 12],
    [40, 25],
    [60, 55],
    [80, 10],
    [100, 0]
  ];
</script>
```

**Comment by jcfranco** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/calcite-5f7d10460071bf0024e66277/issues/Esri/calcite-components/2914?planning-poker) with ZenHub @caripizza

**Comment by y0n4** [comment]
I found out that one of the reason why the histogram is not matching the negative points accurately is because the `calcite-graph` range is basing it off from the histogram data (taken from the above example use case)
```
    [0, 0],
    [20, 12],
    [40, 25],
    [60, 55],
    [80, 10],
    [100, 0]
```
Notice that 0 is actually not the lowest range- it's where the histogram actually starts but calcite-graph is reads this data as the lowest range instead of accessing the prop `min="-100`.

If we add `[-100, 0]` above `[0, 0]`, then it would be fine... but do we want that? It totally disregards the provided min range which is -100 in this case.

**Comment by caripizza** [comment]
The fix doesn't seem to work if the slider histogram has a max and maxValue equal to 0. Does that sound correct @y0n4, or do I need to modify the histogram data to be different? Can you please clarify?

```html
    <calcite-slider
      min="-100"
      max="0"
      min-value="-100"
      max-value="0"
      step="1"
      min-label="Temperature range (lower)"
      max-label="Temperature range (upper)"
      class="js-histogram"
      label-handles
    ></calcite-slider>
    <script>
      document.querySelector(".slider-ex").histogram = [
        [0, 0],
        [20, 12],
        [40, 25],
        [60, 55],
        [80, 10],
        [100, 0]
      ];
    </script>
```

![image](https://user-images.githubusercontent.com/42423180/139907293-c1a5fbb5-4408-42a5-b718-964a33424f92.png)

**Comment by y0n4** [comment]
So there are two issues here. @caripizza 
One, which I just realized is that the histogram is not getting highlighted between -100, 0 because there is no histogram data between -100 to 0 so it should just be a flat line as it is showing here as expected.

Second which is the true bug I see is that the histogram showing between -100, 0 is not supposed to be there because the histogram data only shows from 0, 100. That issue should be fixed in the next pr #3452

**Comment by benelan** [comment]
@y0n4 the snippet that Cari provided in her [comment above](https://github.com/Esri/calcite-components/issues/2914#issuecomment-957926448) still doesn't work. Is something being done wrong in the sample? Here is her code: https://codepen.io/benesri/pen/dyzQdJY

**Comment by caripizza** [comment]
@benelan Sorry for the confusion here. Yona clarified to me that the histogram array needs to include the slider's minValue when its negative, like this:

```js
slider.histogram =  [
    [-100, 0],
    [-80, 12],
    [-60, 25],
    [-40, 55],
    [-20, 10],
    [0, 0]
  ];
```

Here's an example of the behavior working:
https://github.com/Esri/calcite-components/pull/3087/commits/e561e36eec65294adea880acf0c242c4aea7519f

We did improve the JSDoc description (see https://github.com/Esri/calcite-components/pull/3452#discussion_r746151836) but perhaps a new usage snippet is warranted as well?

**Comment by benelan** [comment]
verified on next
