### ISSUE TITLE
Date Picker - First day of the week is not localized

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#4075]
### Actual Behavior

This was fixed for Russian via this issue: https://github.com/Esri/calcite-components/issues/2291 but it is still an issue for a number of other languages. 

In CS/DA/DE/EL/ES/ET/FI/FR/HR/IT/LT/LV/NL/NB/PL/RO/SR/SV/TR/VI/BS/SL/CA/HU/UK languages, the first day is still Sunday rather than Monday. 

Here is detailed list of languages/locales and their expected First days of the week
https://olga8614.github.io/calendars/

cc @jcfranco @benelan 

### Expected Behavior

First day of the week should be localized. 

### Reproduction Sample

https://codepen.io/zmatheson/pen/ExbWVKb

### Reproduction Steps

1.  Open https://codepen.io/zmatheson/pen/ExbWVKb and note that first day of the week for uk locale is Sunday not Monday. 

### Reproduction Version

@esri/calcite-components@1.0.0-VERSION

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-VERSION`

### Source

- [ ] CDN
- [ ] NPM package

**Comment by macandcheese** [comment]
In addition to updating the defaults above, A nice quality of life feature would be to allow configuration of a "week start day" option. 

This is referenced in this example as `start-weekday`: https://bootstrap-vue.org/docs/components/form-datepicker

**Comment by jcfranco** [comment]
@macandcheese Can you submit a separate enhancement ticket for that? It's out of scope for the original request.

**Comment by jcfranco** [comment]
@zaramatheson @olga8614 We have 2 locale files that are missing from https://olga8614.github.io/calendars/: 

* MK – updated according to https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/weekData.json#L153
* HI – left as is (starting on Sunday) according to https://happydays365.org/days-of-the-week/weekdays-in-hindi/#:~:text=The%20first%20day%20of%20the,%E2%80%9CMangalwar.%E2%80%9D%20The%20fourth%20day

Is the above correct?

**Comment by Olga8614** [comment]
@jcfranco I have compiled my list of First Days of the Week based on our Locale Lookup tool, that has a lot of different locales.
You can find it here: https://i18n.esri.com/website/landing
Please go to i18n Data and Tools -> Tools
![image](https://user-images.githubusercontent.com/29614798/154329962-daad4510-f061-42f4-96f9-8df018f9696e.png)

**Comment by Olga8614** [comment]
(you need to be on esri VPN and sign in with AVWORLD account to see the Locale Lookup Tool)

**Comment by jcfranco** [comment]
@Olga8614 That's awesome, thanks for sharing!

**Comment by jcfranco** [comment]
Installed!

**Comment by benelan** [comment]
@Olga8614 or @zaramatheson can you please help verify that this issue is fixed on `next`. I'm not sure what I'm looking at.

**Comment by Olga8614** [comment]
We verified this defect on AGOL 10.1 devext and qaext site (3/3/2022) in CZ/DA/DE/EL/TR language with FF/Safari/Chrome/Edge(Chromium) browsers. The first day is still Sunday rather than Monday on calendar on time slider options pane. Please refer to "https://github.com/ArcGIS/I18N-BYS-Bugs/issues/7699.jpg" So this defect is not fixed. Thanks!
![image](https://user-images.githubusercontent.com/29614798/156871214-7c843806-1bd3-45cb-b1f6-dd313eea53f5.png)

**Comment by zaramatheson** [comment]
@Olga8614 This fix hasn't made it into MV yet. @benelan or @jcfranco Can you direct us to how to verify this on next?

**Comment by AdelheidF** [comment]
@zaramatheson  if you change your codepen to use this below instead of `next`, you can pick the calcite version to use. The latest is beta.78.

```
  <script type="module" src=https://js.arcgis.com/calcite-components/1.0.0-beta.78/calcite.esm.js> </script>
  <link rel="stylesheet" type="text/css" href=https://js.arcgis.com/calcite-components/1.0.0-beta.78/calcite.css />
```

**Comment by benelan** [comment]
Hi @zaramatheson and @Olga8614! Did you get a chance to verify this issue? It is now available on `beta.80` as well.

```html
<script type="module" src="https://js.arcgis.com/calcite-components/1.0.0-beta.80/calcite.esm.js"></script>
<link rel="stylesheet" type="text/css" href="https://js.arcgis.com/calcite-components/1.0.0-beta.80/calcite.css" />
```

**Comment by zaramatheson** [comment]
@Olga8614  Here is an updated codepen. Can you help verify? 
https://codepen.io/zmatheson/pen/qBpZNqx

If you just edit the locale here, it should update:
![image](https://user-images.githubusercontent.com/50747646/159057007-3a4d48ca-bc2e-486d-9402-b615e80c1c24.png)

**Comment by Olga8614** [comment]
Updated codepen works good to me

**Comment by benelan** [comment]
thanks for confirming!
