### ISSUE TITLE
Enhancement: Don't allow invalid characters in Calcite inputs

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#961]
Issue from Map Viewer Beta Time Slider testing: 

https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/1952

The date and number drop down inputs allow users to enter any character. In this example, the date should only allow date values & the count should only allow number values. 

![image](https://user-images.githubusercontent.com/50747646/92771389-b3a32180-f34f-11ea-9502-16a79353e04b.png)

You can see the issue in Map VIewer Beta using this map:

https://devtesting.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=8905c23769374afdb7057ec257fc8a6b

Time configuration panel is accessed from the Map Propertie button on left panel > Time Slider Options

![image](https://user-images.githubusercontent.com/50747646/92772124-4fcd2880-f350-11ea-964d-52cb9ca36e93.png)

cc @jcfranco

**Comment by macandcheese** [comment]
@zaramatheson - what browsers does this appear in? I know that is how native browser inputs behave in Safari (for all three), and Firefox (for number)

Time: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
Number: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
Date: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

I'm not sure if we want to validate on the component side since we should probably match what browsers do by default, but end users can validate or use `pattern=`.

**Comment by zaramatheson** [comment]
@macandcheese  I see the issue in both Firefox and Chrome at least. 
![image](https://user-images.githubusercontent.com/50747646/100803284-c291f100-33df-11eb-81f8-9e6f4f9d15a6.png)

**Comment by macandcheese** [comment]
Hm, I'm unable to reproduce the "test" in the Count input in Chrome: [storybook example](https://esri.github.io/calcite-components/?path=/story/components-input--with-label&knob-status=idle&knob-scale=m&knob-label%20text=My%20great%20label&knob-type=number&knob-alignment=start&knob-number-button-type=horizontal&knob-min=0&knob-max=100&knob-step=1&knob-prefix-text=&knob-suffix-text=&knob-loading=&knob-clearable=&knob-disabled=&knob-value=&knob-placeholder=Placeholder%20text&knob-input-message-active=&knob-input%20message%20type=default&knob-input%20message%20status=idle&knob-input%20message%20text=My%20great%20input%20message)

Note: text being entered in the number type input would be expected in other browsers like Safari / Firefox (see link in above comment to Moz docs on native input type number). So, I think that's better handled as something on the app-side of things.

As far as date - if those are using calcite-date, that's also expected (although perhaps not desired) behavior, because the date component doesn't use "type=date" for an input..

That would actually be a calcite-date issue / enhancement (since that is a component where handling validation on our end for that could be possible), I think a valid one if you want to open that.

**Comment by macandcheese** [comment]
@zaramatheson  - Just following up here - I think this should be cleared up by now - feel free to close if so.

**Comment by macandcheese** [comment]
@zaramatheson I think the above was addressed in some past updates - there's now the time picker input, and this PR should disallow entry of text in number input : https://github.com/Esri/calcite-components/pull/2128

**Comment by Olga8614** [comment]
We verified this defect on ArcGIS Online 2024.r01 early devext site (2/4/2024) in ENU language with Edge Chromium/Chrome/FF/Safari browsers.

Invalid characters can be added in textbox of Start/End date and Start/End time. -not fixed.
Invalid characters can not be added intextbox of Count. -fixed
So this defect is partly fixed. Thanks!
